# Generated by Django 4.0 on 2021-12-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVRIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avr_scheme', models.TextField()),
                ('article', models.TextField()),
                ('name', models.TextField()),
                ('power_devices_brand', models.TextField()),
                ('power_devices_type', models.TextField()),
                ('spring_time', models.TextField()),
                ('plc', models.TextField()),
                ('extension_module', models.TextField()),
                ('specification', models.TextField()),
                ('documentation', models.TextField()),
                ('specification_link', models.TextField()),
                ('xlsx_export_link', models.TextField()),
                ('pdf_avr_link', models.TextField()),
                ('pdf_scheme_link', models.TextField()),
                ('zip_link', models.TextField()),
                ('xlsx_link', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AVRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('avr_scheme', models.TextField()),
                ('power_part', models.TextField()),
                ('plc_voltage', models.TextField()),
                ('brand', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AVRSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField()),
                ('name', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AVRSpecData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('item', models.TextField()),
                ('value', models.TextField()),
                ('avr_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avr.avrspec')),
            ],
        ),
    ]
