# Generated by Django 4.0 on 2021-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avrindex',
            name='extension_module',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='spring_time',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
