# Generated by Django 4.0 on 2021-12-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr', '0003_alter_avrindex_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avrindex',
            name='status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
