# Generated by Django 4.0 on 2021-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr', '0004_alter_avrindex_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVRLog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('avr_scheme', models.CharField(max_length=5)),
                ('power_part', models.CharField(max_length=30)),
                ('plc_voltage', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AVRLog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ua', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AVRLog3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=5)),
                ('info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AVRLog',
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='article',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='avr_scheme',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='extension_module',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='plc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='power_devices_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='power_devices_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='specification',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avrindex',
            name='spring_time',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
