# Generated by Django 4.0 on 2021-12-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr', '0005_avrlog1_avrlog2_avrlog3_delete_avrlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avrlog1',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avrlog2',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avrlog3',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
